name: flutter_cspell
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  dart_cspell_cli:
    git:
      url: https://github.com/fa0311/dart_cspell_cli.git
      ref: main
